oengus:
    jwt:
        secret: ${JWT_SECRET}
        expiration: 604800
    baseUrl: ${BASE_URL}
    oauthOrigins: ${OAUTH_ORIGINS}
    shortUrl: "https://oengus.fun"
    pageSize: ${PAGINATION_SIZE:15}

discord:
    clientId: ${DISCORD_CLIENT_ID}
    clientSecret: ${DISCORD_CLIENT_SECRET}
    grantType: 'authorization_code'
    redirectUri: '/login/discord'
    syncRedirectUri: '/user/settings/sync/discord'
    scope:
        - identify
    botTokenRaw: ${DISCORD_BOT_TOKEN}
    botToken: 'Bot ${DISCORD_BOT_TOKEN}'

twitter:
    oauth:
        # oauth2
        clientId: ${TWITTER_OAUTH2_CLIENT_ID}
        clientSecret: ${TWITTER_OAUTH2_CLIENT_SECRET}
        redirectUri: '/login/twitter'
        syncRedirectUri: '/user/settings/sync/twitter'
        grantType: 'authorization_code'
        scope:
            - users.read
            - tweet.read
        # oauth 1.0a
        consumerKey: ${TWITTER_CONSUMER_KEY}
        consumerSecret: ${TWITTER_CONSUMER_SECRET}
        accessToken: ${TWITTER_ACCESS_TOKEN}
        accessTokenSecret: ${TWITTER_ACCESS_TOKEN_SECRET}

paypal:
    clientId: ${PAYPAL_CLIENT_ID}
    clientSecret: ${PAYPAL_CLIENT_SECRET}

twitch:
    login:
        clientId: ${TWITCH_CLIENT_ID}
        clientSecret: ${TWITCH_CLIENT_SECRET}
        grantType: 'authorization_code'
        redirectUri: '/login/twitch'
        syncRedirectUri: '/user/settings/sync/twitch'
        scope:
            - openid

server:
    undertow:
        accesslog:
            enabled: false
    error:
        whitelabel:
            enabled: true

sentry:
    dsn: ${SENTRY_DSN}
    # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
    # We recommend adjusting this value in production.
    traces-sample-rate: ${SENTRY_TRACES_SAMPLE_RATE:1.0}
    environment: ${SENTRY_ENVIRONMENT}
    exception-resolver-order: 100

spring:
    # TODO: read into this, cache can do a lot
    # https://www.ehcache.org/documentation/3.3/107.html
    # https://github.com/gibsong/ehcache-jsr107-spring/tree/master/src/main/resources
#    cache:
#        cache-names:
#            - scheduleCache
#        jcache:
#            config: classpath:ehcache.xml
#            provider: org.ehcache.jsr107.EhcacheCachingProvider
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: false
        properties:
            javax:
                persistence:
                    sharedCache:
                        # javax.persistence.SharedCacheMode
                        mode: ${SHARED_CACHE_MODE:NONE}
#                        mode: ENABLE_SELECTIVE
            hibernate:
                javax:
                    cache:
                        missing_cache_strategy: create
#                cache:
#                    # disable database caching
#                    use_second_level_cache: ${USE_SECOND_LEVEL_CACHE:false}
#                    use_query_cache: ${USE_QUERY_CACHE:false}
#                    provider: org.ehcache.jsr107.EhcacheCachingProvider
#                    region:
#                        factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
                dialect: org.hibernate.dialect.PostgreSQL82Dialect
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
                temp:
                    use_jdbc_metadata_defaults: false
        open-in-view: true
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        hikari:
            # Use 4 connections and leave the others for other applications
            maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE:4}
            connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:30000}
            idle-timeout: ${HIKARI_IDLE_TIMEOUT:600000}
            max-lifetime: ${HIKARI_MAX_LIFETIME:1800000}
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.xml
    jackson:
        mapper:
            DEFAULT_VIEW_INCLUSION: true
        deserialization:
            USE_BIG_DECIMAL_FOR_FLOATS: true
    mvc:
        throw-exception-if-no-handler-found: true
    web:
        resources.add-mappings: false

springdoc:
    packages-to-scan: app.oengus.web
    pathsToMatch: /**

management:
    endpoints:
        web:
            exposure:
                include:
                    - prometheus
                    - health

log4j:
    logger:
        org:
            hibernate: info

debug: false
