name: Bug Report
description: Something is not working correctly on Oengus, tell us about it
title: ""
labels: [bug]
issue_body: true
body:
    - type: input
      attributes:
          label: Describe the bug
          description: "A clear and concise description of what the bug is."
          placeholder: "When I try to visit the site I get the following error: It's not a bug, it's a feature"
      validations:
          required: true

    - type: textarea
      attributes:
        label: How to reproduce
        description: "How do you trigger this bug? Please be as detailed as possible"
        value: |
            1. Go to '.....................'
            2. Click on '..................'
            3. Scroll down to '............'
            4. Error message displays '....'
            ...
      validations:
        required: true

    - type: input
      attributes:
          label: Expected behavior
          description: "What do you expect to happen instead?"
          placeholder: "The error message should not pop up as it's not a bug, but a feature"
      validations:
          required: true

    - type: textarea
      attributes:
          label: Desktop (please complete the following information)
          description: "If not applicable leave empty"
          placeholder: "Isn't it all just chrome these days?\nYes, 2004 19041.804 is an actual windows 10 version, it was what I ran at the time of writing this"
          value: |
              - OS: [e.g. iOS, Ubuntu, Windows]
              - Browser [e.g. chrome, safari, firefox]
              - Version [e.g. 22, 20.04, 2004 19041.804]

    - type: textarea
      attributes:
          label: Smartphone (please complete the following information)
          description: "If not applicable leave empty"
          value: |
              - Device: [e.g. iPhone6]
              - OS: [e.g. iOS8.1]
              - Browser [e.g. stock browser, safari]
              - Version [e.g. 22]

    - type: textarea
      attributes:
          label: Additional context/screenshots
          description: |
              Add any other context about the problem here.
              Screenshots can be uploaded in the text field below this form

