name: Test PR
on:
    push:
        branches-ignore:
            - master
    pull_request:
jobs:
    build_docker_file:

        concurrency:
            group: ${{ github.ref }}
            cancel-in-progress: true

        name: Build docker image
        runs-on: ubuntu-latest
        steps:
            -   name: Check out the repo
                uses: actions/checkout@v2
                with:
                    submodules: true

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            -   name: Build and push
                id: docker_build
                uses: docker/build-push-action@v2
                with:
                    context: .
                    push: false
                    cache-from: type=local,src=/tmp/.buildx-cache
                    cache-to: type=local,dest=/tmp/.buildx-cache-new

            # Temp fix
            # https://github.com/docker/build-push-action/issues/252
            # https://github.com/moby/buildkit/issues/1896
            -   name: Move cache
                run: |
                    rm -rf /tmp/.buildx-cache
                    mv /tmp/.buildx-cache-new /tmp/.buildx-cache

            -   name: Image digest
                run: echo ${{ steps.docker_build.outputs.digest }}
