name: Publish prod
on:
    release:
        types: [ published ]
jobs:
    push_to_registry:

        concurrency:
            group: ${{ github.ref }}
            cancel-in-progress: true

        name: Push production image
        runs-on: ubuntu-latest
        steps:
            -   name: Check out the repo
                uses: actions/checkout@v2
                with:
                    submodules: true

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            -   name: Login to Docker
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_TOKEN }}

            -   name: Build and push
                id: docker_build
                uses: docker/build-push-action@v2
                with:
                    context: .
                    push: true
                    tags: oengusio/backend:latest
                    cache-from: type=local,src=/tmp/.buildx-cache
                    cache-to: type=local,dest=/tmp/.buildx-cache-new

            # Temp fix
            # https://github.com/docker/build-push-action/issues/252
            # https://github.com/moby/buildkit/issues/1896
            -   name: Move cache
                run: |
                    rm -rf /tmp/.buildx-cache
                    mv /tmp/.buildx-cache-new /tmp/.buildx-cache

            -   name: Image digest
                run: echo ${{ steps.docker_build.outputs.digest }}

            -   name: Trigger prod webhook
                uses: zzzze/webhook-trigger@v1.0.0
                with:
                    webhook_url: ${{ secrets.PROD_WEBHOOK_URL }}

            -   name: Trigger sandbox webhook
                uses: zzzze/webhook-trigger@v1.0.0
                with:
                    webhook_url: ${{ secrets.SANDBOX_WEBHOOK_URL }}
